# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [10]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
# Import torch
import torch


# Create random tensor
r_tensor_1 = torch.rand([7,7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
r_tensor_2 = torch.rand([1,7])
# Perform matrix multiplication 
torch.matmul(r_tensor_1, r_tensor_2.T)

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(seed = 0)

# Create two random tensors
r_tensor_3 = torch.rand([7,7])
r_tensor_4 = torch.rand([1,7])

# Matrix multiply tensors
torch.matmul(r_tensor_3, r_tensor_4.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"


# Create two random tensors on GPU
tensor_1 = torch.rand([2,3]).to(device)
tensor_2 = torch.rand([2,3]).to(device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(tensor_1, tensor_2.T)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(torch.max(torch.matmul(tensor_1, tensor_2.T)))
# Find min
print(torch.min(torch.matmul(tensor_1, tensor_2.T)))


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(torch.argmax(torch.matmul(tensor_1, tensor_2.T)))


# Find arg min
print(torch.argmin(torch.matmul(tensor_1, tensor_2.T)))


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(7)  # Set the random seed to 7

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_removed = tensor.squeeze()

# Print out tensors and their shapesprint("Original Tensor:")
print(tensor)
print("Shape:", tensor.shape)

print("\nTensor with Removed Dimensions:")
print(tensor_removed)
print("Shape:", tensor_removed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])

Tensor with Removed Dimensions:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape: torch.Size([10])
